name: Update Today's Commit Counter

on:
  schedule:
    - cron: '0 0 * * *'  # runs every day at midnight UTC
  workflow_dispatch:     # allows manual trigger

jobs:
  update_commit_counter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get today's commit count
        id: commit_count
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get today's date in UTC (format: YYYY-MM-DD)
          TODAY=$(date -u +'%Y-%m-%d')
          echo "Today's date: $TODAY"
          # Use GitHub CLI (pre-installed on ubuntu-latest) to paginate through commits of this repo on today's date
          COUNT=$(gh api repos/${{ github.repository }}/commits --paginate --jq "[.[] | select(.commit.author.date | startswith(\"$TODAY\"))] | length")
          echo "::set-output name=count::$COUNT"
          echo "Today's commit count is: $COUNT"

      - name: Update README.md with today's commit count
        run: |
          # Replace the number after 'Today Commit Count:' with the new count
          sed -i "s/Today Commit Count: \\*\\*[0-9]\\+\\*\\*/Today Commit Count: **${{ steps.commit_count.outputs.count }}**/" README.md

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update today's commit count: ${{ steps.commit_count.outputs.count }}" || exit 0
          git push
